#!/bin/sh
# SPDX-FileCopyrightText: 2022-2026 Proton AG
# SPDX-License-Identifier: GPL-3.0-or-later

set -e
case "$1" in
    remove|purge)
        if ! ks_error=$(busctl call \
                me.proton.vpn.kill_switch /me/proton/vpn/kill_switch \
                me.proton.vpn.kill_switch Disable 2>&1); then
            echo "warning: could not disable the Proton VPN kill switch: ${ks_error}" >&2
        fi
        ;;
esac

#DEBHELPER#

exit 0
