#!/usr/bin/python3
# SPDX-FileCopyrightText: 2026 Plasma VPN contributors
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate the Python and C++ snapshot contract from one checked-in schema."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = PROJECT_ROOT / "data" / "snapshot-schema-v2.json"
PYTHON_OUTPUT = (
    PROJECT_ROOT / "backend" / "proton_vpn_kde_backend" / "snapshot_contract.py"
)
CPP_OUTPUT = PROJECT_ROOT / "src" / "SnapshotContract.generated.h"
SUPPORTED_TYPES = {"boolean", "integer", "string"}


def load_schema() -> tuple[int, list[tuple[str, str]]]:
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    version = schema.get("schemaVersion")
    fields = schema.get("fields")
    if type(version) is not int or not isinstance(fields, dict) or not fields:
        raise ValueError("Snapshot schema must define an integer version and fields")
    records: list[tuple[str, str]] = []
    for name, field_type in fields.items():
        if not isinstance(name, str) or field_type not in SUPPORTED_TYPES:
            raise ValueError(f"Invalid snapshot field declaration: {name!r}")
        records.append((name, field_type))
    if dict(records).get("schemaVersion") != "integer":
        raise ValueError("Snapshot schemaVersion must be a required integer field")
    return version, records


def render_python(version: int, fields: list[tuple[str, str]]) -> str:
    lines = [
        "# SPDX-FileCopyrightText: 2026 Plasma VPN contributors",
        "# SPDX-License-Identifier: GPL-3.0-or-later",
        "",
        '"""Generated validation for the versioned state snapshot contract."""',
        "",
        "# Generated by scripts/generate-snapshot-contract.py; do not edit.",
        f"SNAPSHOT_SCHEMA_VERSION = {version}",
        "SNAPSHOT_FIELD_TYPES = {",
    ]
    lines.extend(f'    "{name}": "{field_type}",' for name, field_type in fields)
    lines.extend(
        [
            "}",
            "",
            "",
            "def validate_snapshot_payload(payload: dict[str, object]) -> None:",
            "    expected = set(SNAPSHOT_FIELD_TYPES)",
            "    actual = set(payload)",
            "    if actual != expected:",
            "        missing = sorted(expected - actual)",
            "        extra = sorted(actual - expected)",
            "        raise ValueError(",
            '            f"Snapshot fields differ from the versioned contract: "',
            '            f"missing={missing}, extra={extra}"',
            "        )",
            "    for name, field_type in SNAPSHOT_FIELD_TYPES.items():",
            "        value = payload[name]",
            '        valid = type(value) is bool if field_type == "boolean" else (',
            '            type(value) is int if field_type == "integer" else (',
            "                isinstance(value, str)",
            "            )",
            "        )",
            "        if not valid:",
            "            raise ValueError(",
            '                f"Snapshot field {name!r} must be {field_type}"',
            "            )",
            "",
        ]
    )
    return "\n".join(lines)


def render_cpp(version: int, fields: list[tuple[str, str]]) -> str:
    enum_values = {"boolean": "Boolean", "integer": "Integer", "string": "String"}
    lines = [
        "// SPDX-FileCopyrightText: 2026 Plasma VPN contributors",
        "// SPDX-License-Identifier: GPL-3.0-or-later",
        "",
        "// Generated by scripts/generate-snapshot-contract.py; do not edit.",
        "#pragma once",
        "",
        "#include <QJsonObject>",
        "#include <QString>",
        "#include <array>",
        "#include <cmath>",
        "",
        "namespace ProtonVpnKde",
        "{",
        f"inline constexpr int snapshotSchemaVersion = {version};",
        "enum class SnapshotFieldType { Boolean, Integer, String };",
        "struct SnapshotField { const char *name; SnapshotFieldType type; };",
        f"inline constexpr std::array<SnapshotField, {len(fields)}> snapshotFields{{{{",
    ]
    lines.extend(
        f'    {{"{name}", SnapshotFieldType::{enum_values[field_type]}}},'
        for name, field_type in fields
    )
    lines.extend(
        [
            "}};",
            "",
            f"inline bool validateSnapshotV{version}(const QJsonObject &snapshot,",
            "                               QString *errorMessage = nullptr)",
            "{",
            "    if (snapshot.size() != static_cast<qsizetype>(snapshotFields.size())) {",
            "        if (errorMessage) {",
            "            *errorMessage = QStringLiteral(\"Snapshot has missing or extra fields\");",
            "        }",
            "        return false;",
            "    }",
            "    for (const auto &field : snapshotFields) {",
            "        const auto value = snapshot.value(QString::fromLatin1(field.name));",
            "        const bool valid = field.type == SnapshotFieldType::Boolean",
            "            ? value.isBool()",
            "            : field.type == SnapshotFieldType::String",
            "            ? value.isString()",
            "            : value.isDouble()",
            "                && std::trunc(value.toDouble()) == value.toDouble();",
            "        if (!valid) {",
            "            if (errorMessage) {",
            "                *errorMessage = QStringLiteral(\"Missing or invalid snapshot field: %1\")",
            "                                    .arg(QString::fromLatin1(field.name));",
            "            }",
            "            return false;",
            "        }",
            "    }",
            "    return true;",
            "}",
            "} // namespace ProtonVpnKde",
            "",
        ]
    )
    return "\n".join(lines)


def update(path: Path, content: str, *, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == content:
        return True
    if check:
        print(f"Generated snapshot contract is stale: {path}")
        return False
    path.write_text(content, encoding="utf-8")
    print(f"Updated {path}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    version, fields = load_schema()
    results = (
        update(PYTHON_OUTPUT, render_python(version, fields), check=args.check),
        update(CPP_OUTPUT, render_cpp(version, fields), check=args.check),
    )
    return 0 if all(results) else 1


if __name__ == "__main__":
    raise SystemExit(main())
