#!/usr/bin/python3
# SPDX-FileCopyrightText: 2026 Plasma VPN contributors
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate language constants from the checked-in D-Bus contracts."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import difflib
from pathlib import Path
import re
import sys
import xml.etree.ElementTree as ET


PROJECT_ROOT = Path(__file__).resolve().parent.parent
CONTRACT_DIRECTORY = PROJECT_ROOT / "data" / "dbus"
CPP_OUTPUT = PROJECT_ROOT / "src" / "DbusContract.h"
PYTHON_OUTPUT = PROJECT_ROOT / "backend" / "proton_vpn_kde_backend" / "dbus_contract.py"
BUS_ANNOTATION = "quest.entropy.PlasmaVPN.BusName"
AUTHORIZATION_ANNOTATION = "quest.entropy.PlasmaVPN.Authorization"
SECRET_ANNOTATION = "quest.entropy.PlasmaVPN.SecretDescriptor"
ERROR_ANNOTATION_PREFIX = "quest.entropy.PlasmaVPN.Error."
AUTHORIZATION_CLASSES = frozenset({"handshake", "protected", "read-only"})


@dataclass(frozen=True)
class Method:
    name: str
    authorization: str | None
    secret_descriptor: bool


@dataclass(frozen=True)
class Contract:
    namespace: str
    bus_name: str
    object_path: str
    interface_name: str
    methods: tuple[Method, ...]
    signals: tuple[str, ...]
    errors: tuple[tuple[str, str], ...]


def _annotation(element: ET.Element, name: str) -> str | None:
    annotation = element.find(f"annotation[@name='{name}']")
    return None if annotation is None else annotation.attrib.get("value")


def _constant_name(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).upper()


def _member_name(name: str) -> str:
    return name[:1].lower() + name[1:]


def _load_contract(filename: str, namespace: str) -> Contract:
    path = CONTRACT_DIRECTORY / filename
    root = ET.parse(path).getroot()
    if root.tag != "node" or not root.attrib.get("name"):
        raise ValueError(f"{path}: expected one named D-Bus node")
    interfaces = root.findall("interface")
    if len(interfaces) != 1 or not interfaces[0].attrib.get("name"):
        raise ValueError(f"{path}: expected exactly one named interface")
    interface = interfaces[0]
    bus_name = _annotation(interface, BUS_ANNOTATION)
    if not bus_name:
        raise ValueError(f"{path}: missing {BUS_ANNOTATION}")

    methods: list[Method] = []
    seen_names: set[str] = set()
    for element in interface.findall("method"):
        name = element.attrib.get("name", "")
        if not name or name in seen_names:
            raise ValueError(f"{path}: method names must be non-empty and unique")
        seen_names.add(name)
        authorization = _annotation(element, AUTHORIZATION_ANNOTATION)
        if namespace == "Backend" and authorization not in AUTHORIZATION_CLASSES:
            raise ValueError(f"{path}: {name} has no valid authorization class")
        secret_descriptor = _annotation(element, SECRET_ANNOTATION) == "true"
        input_descriptors = [
            argument
            for argument in element.findall("arg")
            if argument.attrib.get("direction", "in") == "in"
            and argument.attrib.get("type") == "h"
        ]
        if secret_descriptor != bool(input_descriptors):
            raise ValueError(
                f"{path}: {name} secret annotation does not match its descriptor"
            )
        methods.append(Method(name, authorization, secret_descriptor))

    signals = tuple(element.attrib["name"] for element in interface.findall("signal"))
    if len(signals) != len(set(signals)):
        raise ValueError(f"{path}: signal names must be unique")

    errors: list[tuple[str, str]] = []
    for element in interface.findall("annotation"):
        annotation_name = element.attrib.get("name", "")
        if annotation_name.startswith(ERROR_ANNOTATION_PREFIX):
            errors.append(
                (
                    annotation_name.removeprefix(ERROR_ANNOTATION_PREFIX),
                    element.attrib["value"],
                )
            )

    return Contract(
        namespace=namespace,
        bus_name=bus_name,
        object_path=root.attrib["name"],
        interface_name=interface.attrib["name"],
        methods=tuple(methods),
        signals=signals,
        errors=tuple(errors),
    )


def _contracts() -> tuple[Contract, ...]:
    return (
        _load_contract("quest.entropy.PlasmaVPN.Backend1.xml", "Backend"),
        _load_contract("quest.entropy.PlasmaVPN.Agent1.xml", "Agent"),
        _load_contract("quest.entropy.PlasmaVPN.ControlCenter1.xml", "ControlCenter"),
    )


def _render_cpp(contracts: tuple[Contract, ...]) -> str:
    lines = [
        "// SPDX-FileCopyrightText: 2026 Plasma VPN contributors",
        "// SPDX-License-Identifier: GPL-3.0-or-later",
        "",
        "// Generated by scripts/generate-dbus-contracts.py; do not edit.",
        "#pragma once",
        "",
        (
            '#define PROTON_VPN_KDE_DBUS_AGENT_INTERFACE '
            f'"{contracts[1].interface_name}"'
        ),
        (
            '#define PROTON_VPN_KDE_DBUS_CONTROL_CENTER_INTERFACE '
            f'"{contracts[2].interface_name}"'
        ),
        "",
        "namespace ProtonVpnKde::DBusContract",
        "{",
    ]
    for contract in contracts:
        lines.extend(
            [
                f"namespace {contract.namespace}",
                "{",
                f'inline constexpr char serviceName[] = "{contract.bus_name}";',
                f'inline constexpr char objectPath[] = "{contract.object_path}";',
                f'inline constexpr char interfaceName[] = "{contract.interface_name}";',
                "",
                "namespace Method",
                "{",
            ]
        )
        for method in contract.methods:
            lines.append(
                f'inline constexpr char {_member_name(method.name)}[] = "{method.name}";'
            )
        lines.extend(["}", ""])
        if contract.signals:
            lines.extend(["namespace Signal", "{"])
            for signal_name in contract.signals:
                lines.append(
                    f"inline constexpr char {_member_name(signal_name)}[] = "
                    f'"{signal_name}";'
                )
            lines.extend(["}", ""])
        if contract.errors:
            lines.extend(["namespace Error", "{"])
            for error_name, value in contract.errors:
                declaration = (
                    f"inline constexpr char {_member_name(error_name)}[] ="
                )
                if len(declaration) + len(value) + 4 > 100:
                    lines.extend([declaration, f'    "{value}";'])
                else:
                    lines.append(f'{declaration} "{value}";')
            lines.extend(["}", ""])
        lines.extend([f"}} // namespace {contract.namespace}", ""])
    lines.extend(["} // namespace ProtonVpnKde::DBusContract", ""])
    return "\n".join(lines)


def _render_python(backend: Contract) -> str:
    classes: dict[str, tuple[str, ...]] = {
        "READ_ONLY_METHODS": tuple(
            method.name
            for method in backend.methods
            if method.authorization == "read-only"
        ),
        "HANDSHAKE_METHODS": tuple(
            method.name
            for method in backend.methods
            if method.authorization == "handshake"
        ),
        "PROTECTED_METHODS": tuple(
            method.name
            for method in backend.methods
            if method.authorization == "protected"
        ),
        "SECRET_DESCRIPTOR_METHODS": tuple(
            method.name for method in backend.methods if method.secret_descriptor
        ),
    }
    lines = [
        "# SPDX-FileCopyrightText: 2026 Plasma VPN contributors",
        "# SPDX-License-Identifier: GPL-3.0-or-later",
        "",
        '"""Generated constants for the Backend1 D-Bus contract."""',
        "",
        "# Generated by scripts/generate-dbus-contracts.py; do not edit.",
        f'BUS_NAME = "{backend.bus_name}"',
        f'OBJECT_PATH = "{backend.object_path}"',
        f'INTERFACE_NAME = "{backend.interface_name}"',
        "",
        "",
        "class Method:",
    ]
    for method in backend.methods:
        lines.append(f'    {_constant_name(method.name)} = "{method.name}"')
    lines.extend(["", "", "class Signal:"])
    for signal_name in backend.signals:
        lines.append(f'    {_constant_name(signal_name)} = "{signal_name}"')
    lines.extend(["", "", "class Error:"])
    for error_name, value in backend.errors:
        lines.append(f'    {_constant_name(error_name)} = "{value}"')
    lines.append("")
    for set_name, names in classes.items():
        lines.extend(["", f"{set_name} = frozenset(", "    {"])
        for name in names:
            lines.append(f"        Method.{_constant_name(name)},")
        lines.extend(["    }", ")"])
    lines.extend(
        [
            "",
            "CLASSIFIED_METHODS = READ_ONLY_METHODS | HANDSHAKE_METHODS | PROTECTED_METHODS",
            "ALL_SIGNALS = frozenset(",
            "    {",
        ]
    )
    for signal_name in backend.signals:
        lines.append(f"        Signal.{_constant_name(signal_name)},")
    lines.extend(["    }", ")", ""])
    return "\n".join(lines)


def _check_output(path: Path, expected: str) -> bool:
    actual = path.read_text(encoding="utf-8") if path.exists() else ""
    if actual == expected:
        return True
    difference = difflib.unified_diff(
        actual.splitlines(),
        expected.splitlines(),
        fromfile=str(path),
        tofile=f"{path} (generated)",
        lineterm="",
    )
    print("\n".join(difference), file=sys.stderr)
    return False


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when checked-in generated files differ from the XML contracts",
    )
    arguments = parser.parse_args()
    contracts = _contracts()
    outputs = {
        CPP_OUTPUT: _render_cpp(contracts),
        PYTHON_OUTPUT: _render_python(contracts[0]),
    }
    if arguments.check:
        return 0 if all(_check_output(*item) for item in outputs.items()) else 1
    for path, content in outputs.items():
        path.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
