# SPDX-FileCopyrightText: 2026 Plasma VPN contributors
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generated constants for the Backend1 D-Bus contract."""

# Generated by scripts/generate-dbus-contracts.py; do not edit.
BUS_NAME = "quest.entropy.PlasmaVPN.Backend"
OBJECT_PATH = "/quest/entropy/PlasmaVPN/Backend"
INTERFACE_NAME = "quest.entropy.PlasmaVPN.Backend1"


class Method:
    AUTHORIZE_CLIENT = "AuthorizeClient"
    BEGIN_FIDO2 = "BeginFido2"
    CANCEL_FIDO2 = "CancelFido2"
    CANCEL_LOGIN = "CancelLogin"
    CONNECT_COUNTRY = "ConnectCountry"
    CONNECT_COUNTRY_WITH_FEATURES = "ConnectCountryWithFeatures"
    CONNECT_FASTEST = "ConnectFastest"
    CONNECT_FASTEST_WITH_FEATURE = "ConnectFastestWithFeature"
    CONNECT_FASTEST_WITH_FEATURES = "ConnectFastestWithFeatures"
    CONNECT_GROUP = "ConnectGroup"
    CONNECT_GROUP_WITH_FEATURES = "ConnectGroupWithFeatures"
    CONNECT_SERVER = "ConnectServer"
    DISABLE_KILL_SWITCH_FOR_LOGIN = "DisableKillSwitchForLogin"
    DISCONNECT = "Disconnect"
    GET_AUTH_PUBLIC_KEY = "GetAuthPublicKey"
    GET_COUNTRIES = "GetCountries"
    GET_CUSTOM_DNS = "GetCustomDns"
    GET_GROUP_SERVERS = "GetGroupServers"
    GET_PENDING_NPS_SURVEY = "GetPendingNpsSurvey"
    GET_SERVER_GROUPS = "GetServerGroups"
    GET_SERVER_LOADS = "GetServerLoads"
    GET_SETTINGS = "GetSettings"
    GET_SNAPSHOT = "GetSnapshot"
    GET_SPLIT_TUNNELING = "GetSplitTunneling"
    LOGIN = "Login"
    LOGOUT = "Logout"
    REGISTER_CLIENT = "RegisterClient"
    SEARCH_LOCATIONS = "SearchLocations"
    SET_RECONNECTION_ENABLED = "SetReconnectionEnabled"
    START_PACKET_CAPTURE = "StartPacketCapture"
    STOP_PACKET_CAPTURE = "StopPacketCapture"
    SUBMIT_FIDO2_PIN = "SubmitFido2Pin"
    SUBMIT_NPS_SURVEY = "SubmitNpsSurvey"
    SUBMIT_SUPPORT_REPORT = "SubmitSupportReport"
    SUBMIT_TWO_FACTOR = "SubmitTwoFactor"
    UNREGISTER_CLIENT = "UnregisterClient"
    UPDATE_CUSTOM_DNS = "UpdateCustomDns"
    UPDATE_SETTINGS = "UpdateSettings"
    UPDATE_SPLIT_TUNNELING = "UpdateSplitTunneling"


class Signal:
    CUSTOM_DNS_CHANGED = "CustomDnsChanged"
    SERVER_DATA_CHANGED = "ServerDataChanged"
    SETTINGS_CHANGED = "SettingsChanged"
    SNAPSHOT_CHANGED = "SnapshotChanged"
    SPLIT_TUNNELING_CHANGED = "SplitTunnelingChanged"


class Error:
    INVALID_CUSTOM_DNS = "quest.entropy.PlasmaVPN.Error.InvalidCustomDns"
    INVALID_SECRET_PAYLOAD = "quest.entropy.PlasmaVPN.Error.InvalidSecretPayload"
    INVALID_SETTINGS = "quest.entropy.PlasmaVPN.Error.InvalidSettings"
    INVALID_SPLIT_TUNNELING = "quest.entropy.PlasmaVPN.Error.InvalidSplitTunneling"
    INVALID_SUPPORT_REPORT = "quest.entropy.PlasmaVPN.Error.InvalidSupportReport"
    OPERATION_FAILED = "quest.entropy.PlasmaVPN.Error.OperationFailed"
    UNAUTHORIZED = "quest.entropy.PlasmaVPN.Error.Unauthorized"


READ_ONLY_METHODS = frozenset(
    {
        Method.GET_COUNTRIES,
        Method.GET_CUSTOM_DNS,
        Method.GET_GROUP_SERVERS,
        Method.GET_SERVER_GROUPS,
        Method.GET_SERVER_LOADS,
        Method.GET_SETTINGS,
        Method.GET_SNAPSHOT,
        Method.GET_SPLIT_TUNNELING,
        Method.SEARCH_LOCATIONS,
    }
)

HANDSHAKE_METHODS = frozenset(
    {
        Method.AUTHORIZE_CLIENT,
        Method.REGISTER_CLIENT,
        Method.UNREGISTER_CLIENT,
    }
)

PROTECTED_METHODS = frozenset(
    {
        Method.BEGIN_FIDO2,
        Method.CANCEL_FIDO2,
        Method.CANCEL_LOGIN,
        Method.CONNECT_COUNTRY,
        Method.CONNECT_COUNTRY_WITH_FEATURES,
        Method.CONNECT_FASTEST,
        Method.CONNECT_FASTEST_WITH_FEATURE,
        Method.CONNECT_FASTEST_WITH_FEATURES,
        Method.CONNECT_GROUP,
        Method.CONNECT_GROUP_WITH_FEATURES,
        Method.CONNECT_SERVER,
        Method.DISABLE_KILL_SWITCH_FOR_LOGIN,
        Method.DISCONNECT,
        Method.GET_AUTH_PUBLIC_KEY,
        Method.GET_PENDING_NPS_SURVEY,
        Method.LOGIN,
        Method.LOGOUT,
        Method.SET_RECONNECTION_ENABLED,
        Method.START_PACKET_CAPTURE,
        Method.STOP_PACKET_CAPTURE,
        Method.SUBMIT_FIDO2_PIN,
        Method.SUBMIT_NPS_SURVEY,
        Method.SUBMIT_SUPPORT_REPORT,
        Method.SUBMIT_TWO_FACTOR,
        Method.UPDATE_CUSTOM_DNS,
        Method.UPDATE_SETTINGS,
        Method.UPDATE_SPLIT_TUNNELING,
    }
)

SECRET_DESCRIPTOR_METHODS = frozenset(
    {
        Method.LOGIN,
        Method.SUBMIT_FIDO2_PIN,
        Method.SUBMIT_NPS_SURVEY,
        Method.SUBMIT_SUPPORT_REPORT,
        Method.SUBMIT_TWO_FACTOR,
    }
)

CLASSIFIED_METHODS = READ_ONLY_METHODS | HANDSHAKE_METHODS | PROTECTED_METHODS
ALL_SIGNALS = frozenset(
    {
        Signal.CUSTOM_DNS_CHANGED,
        Signal.SERVER_DATA_CHANGED,
        Signal.SETTINGS_CHANGED,
        Signal.SNAPSHOT_CHANGED,
        Signal.SPLIT_TUNNELING_CHANGED,
    }
)
