# SPDX-FileCopyrightText: 2026 Plasma VPN contributors
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generated validation for the versioned state snapshot contract."""

# Generated by scripts/generate-snapshot-contract.py; do not edit.
SNAPSHOT_SCHEMA_VERSION = 1
SNAPSHOT_FIELD_TYPES = {
    "schemaVersion": "integer",
    "ready": "boolean",
    "startupCompatible": "boolean",
    "loggedIn": "boolean",
    "authState": "string",
    "accountName": "string",
    "planTitle": "string",
    "userTier": "integer",
    "maxConnections": "integer",
    "fido2Available": "boolean",
    "reconnectEnabled": "boolean",
    "killSwitch": "integer",
    "busy": "boolean",
    "state": "string",
    "errorCode": "string",
    "serverName": "string",
    "serverLocation": "string",
    "exitCountry": "string",
    "entryCountry": "string",
    "forwardedPort": "integer",
    "secureCore": "boolean",
    "tor": "boolean",
    "p2p": "boolean",
    "streaming": "boolean",
    "smartRouting": "boolean",
    "packetCaptureActive": "boolean",
    "coreMemoryOptimized": "boolean",
    "coreVersion": "string",
    "message": "string",
}


def validate_snapshot_payload(payload: dict[str, object]) -> None:
    expected = set(SNAPSHOT_FIELD_TYPES)
    actual = set(payload)
    if actual != expected:
        missing = sorted(expected - actual)
        extra = sorted(actual - expected)
        raise ValueError(
            f"Snapshot fields differ from the versioned contract: "
            f"missing={missing}, extra={extra}"
        )
    for name, field_type in SNAPSHOT_FIELD_TYPES.items():
        value = payload[name]
        valid = type(value) is bool if field_type == "boolean" else (
            type(value) is int if field_type == "integer" else (
                isinstance(value, str)
            )
        )
        if not valid:
            raise ValueError(
                f"Snapshot field {name!r} must be {field_type}"
            )
