// SPDX-FileCopyrightText: 2026 Plasma VPN contributors
// SPDX-License-Identifier: GPL-3.0-or-later

// Generated by scripts/generate-dbus-contracts.py; do not edit.
#pragma once

#define PROTON_VPN_KDE_DBUS_AGENT_INTERFACE "quest.entropy.PlasmaVPN.Agent1"
#define PROTON_VPN_KDE_DBUS_CONTROL_CENTER_INTERFACE "quest.entropy.PlasmaVPN.ControlCenter1"

namespace ProtonVpnKde::DBusContract
{
namespace Backend
{
inline constexpr char serviceName[] = "quest.entropy.PlasmaVPN.Backend";
inline constexpr char objectPath[] = "/quest/entropy/PlasmaVPN/Backend";
inline constexpr char interfaceName[] = "quest.entropy.PlasmaVPN.Backend1";

namespace Method
{
inline constexpr char authorizeClient[] = "AuthorizeClient";
inline constexpr char beginFido2[] = "BeginFido2";
inline constexpr char cancelFido2[] = "CancelFido2";
inline constexpr char cancelLogin[] = "CancelLogin";
inline constexpr char connectCountry[] = "ConnectCountry";
inline constexpr char connectCountryWithFeatures[] = "ConnectCountryWithFeatures";
inline constexpr char connectFastest[] = "ConnectFastest";
inline constexpr char connectFastestWithFeature[] = "ConnectFastestWithFeature";
inline constexpr char connectFastestWithFeatures[] = "ConnectFastestWithFeatures";
inline constexpr char connectGroup[] = "ConnectGroup";
inline constexpr char connectGroupWithFeatures[] = "ConnectGroupWithFeatures";
inline constexpr char connectServer[] = "ConnectServer";
inline constexpr char disableKillSwitchForLogin[] = "DisableKillSwitchForLogin";
inline constexpr char disconnect[] = "Disconnect";
inline constexpr char getAuthPublicKey[] = "GetAuthPublicKey";
inline constexpr char getCountries[] = "GetCountries";
inline constexpr char getCustomDns[] = "GetCustomDns";
inline constexpr char getGroupServers[] = "GetGroupServers";
inline constexpr char getPendingNpsSurvey[] = "GetPendingNpsSurvey";
inline constexpr char getServerGroups[] = "GetServerGroups";
inline constexpr char getServerLoads[] = "GetServerLoads";
inline constexpr char getSettings[] = "GetSettings";
inline constexpr char getSnapshot[] = "GetSnapshot";
inline constexpr char getSplitTunneling[] = "GetSplitTunneling";
inline constexpr char login[] = "Login";
inline constexpr char logout[] = "Logout";
inline constexpr char registerClient[] = "RegisterClient";
inline constexpr char searchLocations[] = "SearchLocations";
inline constexpr char setReconnectionEnabled[] = "SetReconnectionEnabled";
inline constexpr char startPacketCapture[] = "StartPacketCapture";
inline constexpr char stopPacketCapture[] = "StopPacketCapture";
inline constexpr char submitFido2Pin[] = "SubmitFido2Pin";
inline constexpr char submitNpsSurvey[] = "SubmitNpsSurvey";
inline constexpr char submitSupportReport[] = "SubmitSupportReport";
inline constexpr char submitTwoFactor[] = "SubmitTwoFactor";
inline constexpr char unregisterClient[] = "UnregisterClient";
inline constexpr char updateCustomDns[] = "UpdateCustomDns";
inline constexpr char updateSettings[] = "UpdateSettings";
inline constexpr char updateSplitTunneling[] = "UpdateSplitTunneling";
}

namespace Signal
{
inline constexpr char customDnsChanged[] = "CustomDnsChanged";
inline constexpr char serverDataChanged[] = "ServerDataChanged";
inline constexpr char settingsChanged[] = "SettingsChanged";
inline constexpr char snapshotChanged[] = "SnapshotChanged";
inline constexpr char splitTunnelingChanged[] = "SplitTunnelingChanged";
}

namespace Error
{
inline constexpr char invalidCustomDns[] = "quest.entropy.PlasmaVPN.Error.InvalidCustomDns";
inline constexpr char invalidSecretPayload[] = "quest.entropy.PlasmaVPN.Error.InvalidSecretPayload";
inline constexpr char invalidSettings[] = "quest.entropy.PlasmaVPN.Error.InvalidSettings";
inline constexpr char invalidSplitTunneling[] =
    "quest.entropy.PlasmaVPN.Error.InvalidSplitTunneling";
inline constexpr char invalidSupportReport[] = "quest.entropy.PlasmaVPN.Error.InvalidSupportReport";
inline constexpr char operationFailed[] = "quest.entropy.PlasmaVPN.Error.OperationFailed";
inline constexpr char unauthorized[] = "quest.entropy.PlasmaVPN.Error.Unauthorized";
}

} // namespace Backend

namespace Agent
{
inline constexpr char serviceName[] = "quest.entropy.PlasmaVPN.Agent";
inline constexpr char objectPath[] = "/quest/entropy/PlasmaVPN/Agent";
inline constexpr char interfaceName[] = "quest.entropy.PlasmaVPN.Agent1";

namespace Method
{
inline constexpr char ensureRunning[] = "EnsureRunning";
inline constexpr char quit[] = "Quit";
inline constexpr char showControlCenter[] = "ShowControlCenter";
inline constexpr char showSettings[] = "ShowSettings";
}

} // namespace Agent

namespace ControlCenter
{
inline constexpr char serviceName[] = "quest.entropy.PlasmaVPN.ControlCenter";
inline constexpr char objectPath[] = "/quest/entropy/PlasmaVPN/ControlCenter";
inline constexpr char interfaceName[] = "quest.entropy.PlasmaVPN.ControlCenter1";

namespace Method
{
inline constexpr char quit[] = "Quit";
inline constexpr char requestRunnerAction[] = "RequestRunnerAction";
inline constexpr char showControlCenter[] = "ShowControlCenter";
inline constexpr char showSettings[] = "ShowSettings";
}

} // namespace ControlCenter

} // namespace ProtonVpnKde::DBusContract
