// SPDX-FileCopyrightText: 2026 Plasma VPN contributors
// SPDX-License-Identifier: GPL-3.0-or-later

// Generated by scripts/generate-snapshot-contract.py; do not edit.
#pragma once

#include <QJsonObject>
#include <QString>
#include <array>
#include <cmath>

namespace ProtonVpnKde
{
inline constexpr int snapshotSchemaVersion = 1;
enum class SnapshotFieldType { Boolean, Integer, String };
struct SnapshotField { const char *name; SnapshotFieldType type; };
inline constexpr std::array<SnapshotField, 29> snapshotFields{{
    {"schemaVersion", SnapshotFieldType::Integer},
    {"ready", SnapshotFieldType::Boolean},
    {"startupCompatible", SnapshotFieldType::Boolean},
    {"loggedIn", SnapshotFieldType::Boolean},
    {"authState", SnapshotFieldType::String},
    {"accountName", SnapshotFieldType::String},
    {"planTitle", SnapshotFieldType::String},
    {"userTier", SnapshotFieldType::Integer},
    {"maxConnections", SnapshotFieldType::Integer},
    {"fido2Available", SnapshotFieldType::Boolean},
    {"reconnectEnabled", SnapshotFieldType::Boolean},
    {"killSwitch", SnapshotFieldType::Integer},
    {"busy", SnapshotFieldType::Boolean},
    {"state", SnapshotFieldType::String},
    {"errorCode", SnapshotFieldType::String},
    {"serverName", SnapshotFieldType::String},
    {"serverLocation", SnapshotFieldType::String},
    {"exitCountry", SnapshotFieldType::String},
    {"entryCountry", SnapshotFieldType::String},
    {"forwardedPort", SnapshotFieldType::Integer},
    {"secureCore", SnapshotFieldType::Boolean},
    {"tor", SnapshotFieldType::Boolean},
    {"p2p", SnapshotFieldType::Boolean},
    {"streaming", SnapshotFieldType::Boolean},
    {"smartRouting", SnapshotFieldType::Boolean},
    {"packetCaptureActive", SnapshotFieldType::Boolean},
    {"coreMemoryOptimized", SnapshotFieldType::Boolean},
    {"coreVersion", SnapshotFieldType::String},
    {"message", SnapshotFieldType::String},
}};

inline bool validateSnapshotV1(const QJsonObject &snapshot,
                               QString *errorMessage = nullptr)
{
    if (snapshot.size() != static_cast<qsizetype>(snapshotFields.size())) {
        if (errorMessage) {
            *errorMessage = QStringLiteral("Snapshot has missing or extra fields");
        }
        return false;
    }
    for (const auto &field : snapshotFields) {
        const auto value = snapshot.value(QString::fromLatin1(field.name));
        const bool valid = field.type == SnapshotFieldType::Boolean
            ? value.isBool()
            : field.type == SnapshotFieldType::String
            ? value.isString()
            : value.isDouble()
                && std::trunc(value.toDouble()) == value.toDouble();
        if (!valid) {
            if (errorMessage) {
                *errorMessage = QStringLiteral("Missing or invalid snapshot field: %1")
                                    .arg(QString::fromLatin1(field.name));
            }
            return false;
        }
    }
    return true;
}
} // namespace ProtonVpnKde
